bay_pirate_fishing/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^about/', 'bay_pirate_fishing.views.about', name='about'),
    url(r'^schedule/', include('schedule.urls', namespace='schedule')),
    url(r'^$', 'bay_pirate_fishing.views.home', name='home'),
]

schedule/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

schedule/models.py
from django.db import models

class Event(models.Model):
    name = models.CharField("event name", max_length=100)
    location = models.CharField(max_length=100)
    start_date = models.DateField(blank=True)
    end_date = models.DateField(blank=True)
    rank = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

bay_pirate_fishing/views.py
import datetime
from django.shortcuts import render
from schedule.models import Event


def home(request):
    """
    This is the route for the home page of the site.

    :param request: Data passed in from the browser
    :return: Render the template to the browser.
    """

    events = Event.objects.filter(end_date__gte=datetime.date.today())[:3]
    context = {
        'events': events
    }

    return render(request, 'index.html', context)


def about(request):
    """
    This is the route for the about page.

    :param request: Data passed in from the browser
    :return: Render the template to the browser.
    """

    return render(request, 'about.html', {})

schedule/views.py
from django.shortcuts import render
from .models import Event


def index(request):
    events = Event.objects.all()
    context = {
        'events': events
    }
    return render(request, 'schedule/index.html', context)

schedule/templates/schedule/index.html
{% extends 'base.html' %}

{% block page_title %}
    {{ block.super }} | Schedule
{% endblock %}

{% block content %}
    <div class="container">
        <h2 class="text-center">2015 Schedule</h2>

        {% if events %}
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Event name</th>
                        <th>Location</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Ranking</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events %}
                        <tr>
                            <td>{{ event.name }}</td>
                            <td>{{ event.location }}</td>
                            <td>{{ event.start_date }}</td>
                            <td>{{ event.end_date }}</td>
                            <td>{{ event.rank }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <p>No events</p>
        {% endif %}
    </div>
{% endblock %}

templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_title %}
    {{ block.super }} | About
{% endblock %}

{% block page_styles %}
    <link href="{% static 'css/about.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h2 class="text-center">Who we are</h2>

                <p>We are the coolest fishing team in all of Brunswick County.</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block page_title %}Bay Pirate Fishing Team{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block page_styles %}
    {% endblock %}
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">Bay Pirate Fishing Team</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li {% ifequal request.path '/' %}class="active"{% endifequal %}><a href="{% url 'home' %}">Home</a></li>
                        <li {% ifequal request.path '/about/' %}class="active"{% endifequal %}><a href="{% url 'about' %}">About</a></li>
                        <li {% ifequal request.path '/blog/' %}class="active"{% endifequal %}><a href="{% url 'home' %}">Blog</a></li>
                        <li {% ifequal request.path '/schedule/' %}class="active"{% endifequal %}><a href="{% url 'schedule:index' %}">Schedule</a></li>
                    </ul>
                </div><!--/.navbar-collapse -->
            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock %}

    <footer class="footer">
        <div class="container">
            <p>&copy; Company 2014</p>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block page_scripts %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_styles %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="wide">
    
    </div>

    <div class="container middle">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4 col-md-offset-2 col-sm-5 col-sm-offset-1">
                <h2>Recent Posts</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                <p><a class="btn btn-default" href="{% url 'home' %}" role="button">Read more &raquo;</a></p>
            </div>
            <div class="col-md-4 col-sm-5 col-sm-offset-1">
                <h2>Upcoming Events</h2>
                {% if events %}
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Event name</th>
                                    <th>Start date</th>
                                    <th>End date</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for event in events %}
                                    <tr>
                                        <td>{{ event.name }}</td>
                                        <td>{{ event.start_date }}</td>
                                        <td>{{ event.end_date }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <p>No events</p>
                {% endif %}
                <p><a class="btn btn-default" href="{% url 'schedule:index' %}" role="button">Full schedule &raquo;</a></p>
            </div>
        </div>
    </div> <!-- /container -->

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="panel panel-default">
        <div class="container">
            <div class="panel-heading lead text-center">Sponsors</div>

        </div>
    </div>
{% endblock %}